name: py-geospatial
channels:
    - conda-forge
dependencies:
    - numpy
    - shapely
    - fiona
    - matplotlib
    - geopandas
    - pygeos
    - pyproj
    - geopy
    - contextily
    - rasterio
    - geoplot
    - folium
    - scikit-learn
    - osmnx
    - networkx
    - ipympl
    
